/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tsqhjhdbsvtvhgamoyaq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzcWhqaGRic3Z0dmhnYW1veWFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI5MTY1MDMsImV4cCI6MjA3ODQ5MjUwM30.Z178F-lzB6-Tu7xU0fx1QUvOPXXAP0XXPZ-QDUY3gBI"